language: ruby
rvm:
  - 2.2.3
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
