language: ruby
rvm:
  - 2.4.0
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database dawn_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
