language: ruby
rvm:
  - 2.3.1
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -c "create extension postgis"
